### ISSUE TITLE
Overworld - Basic Movement - Mario

### ISSUE THREAD

**Issue by DVectors** [Frakif91/Mario-Luigi#4]
Create basic movement for Mario. Give him the ability to walk and jump.

Animations will need to be created, and billboarding will need to be implemented to ensure the correct animations are playing at specific angles.

**Comment by Frakif91** [comment]
I'll push this afternoon (it's currently 5am for me)

**Comment by Frakif91** [comment]
Finished It !

I'll implement more sprites movement for `controller player` later but it's working for both mario & luigi on the Overworld
